//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Idl.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IIdlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
public partial class IdlBaseListener : IIdlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.idlFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdlFile([NotNull] IdlParser.IdlFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.idlFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdlFile([NotNull] IdlParser.IdlFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.protocolDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocolDeclaration([NotNull] IdlParser.ProtocolDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.protocolDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocolDeclaration([NotNull] IdlParser.ProtocolDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.protocolDeclarationBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocolDeclarationBody([NotNull] IdlParser.ProtocolDeclarationBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.protocolDeclarationBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocolDeclarationBody([NotNull] IdlParser.ProtocolDeclarationBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDeclaration([NotNull] IdlParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDeclaration([NotNull] IdlParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.mainSchemaDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainSchemaDeclaration([NotNull] IdlParser.MainSchemaDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.mainSchemaDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainSchemaDeclaration([NotNull] IdlParser.MainSchemaDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] IdlParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] IdlParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.schemaProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchemaProperty([NotNull] IdlParser.SchemaPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.schemaProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchemaProperty([NotNull] IdlParser.SchemaPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStatement([NotNull] IdlParser.ImportStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStatement([NotNull] IdlParser.ImportStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.namedSchemaDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedSchemaDeclaration([NotNull] IdlParser.NamedSchemaDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.namedSchemaDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedSchemaDeclaration([NotNull] IdlParser.NamedSchemaDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.fixedDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixedDeclaration([NotNull] IdlParser.FixedDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.fixedDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixedDeclaration([NotNull] IdlParser.FixedDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclaration([NotNull] IdlParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclaration([NotNull] IdlParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.enumSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumSymbol([NotNull] IdlParser.EnumSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.enumSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumSymbol([NotNull] IdlParser.EnumSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.enumDefault"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDefault([NotNull] IdlParser.EnumDefaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.enumDefault"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDefault([NotNull] IdlParser.EnumDefaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.recordDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordDeclaration([NotNull] IdlParser.RecordDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.recordDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordDeclaration([NotNull] IdlParser.RecordDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.recordBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordBody([NotNull] IdlParser.RecordBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.recordBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordBody([NotNull] IdlParser.RecordBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaration([NotNull] IdlParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaration([NotNull] IdlParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] IdlParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] IdlParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.messageDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageDeclaration([NotNull] IdlParser.MessageDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.messageDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageDeclaration([NotNull] IdlParser.MessageDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameter([NotNull] IdlParser.FormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameter([NotNull] IdlParser.FormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.resultType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResultType([NotNull] IdlParser.ResultTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.resultType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResultType([NotNull] IdlParser.ResultTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.fullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFullType([NotNull] IdlParser.FullTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.fullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFullType([NotNull] IdlParser.FullTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.plainType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlainType([NotNull] IdlParser.PlainTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.plainType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlainType([NotNull] IdlParser.PlainTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.nullableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullableType([NotNull] IdlParser.NullableTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.nullableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullableType([NotNull] IdlParser.NullableTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] IdlParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] IdlParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] IdlParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] IdlParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.mapType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapType([NotNull] IdlParser.MapTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.mapType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapType([NotNull] IdlParser.MapTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.unionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionType([NotNull] IdlParser.UnionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.unionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionType([NotNull] IdlParser.UnionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonValue([NotNull] IdlParser.JsonValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonValue([NotNull] IdlParser.JsonValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonLiteral([NotNull] IdlParser.JsonLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonLiteral([NotNull] IdlParser.JsonLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonObject([NotNull] IdlParser.JsonObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonObject([NotNull] IdlParser.JsonObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonPair([NotNull] IdlParser.JsonPairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonPair([NotNull] IdlParser.JsonPairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonArray([NotNull] IdlParser.JsonArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonArray([NotNull] IdlParser.JsonArrayContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
