//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Idl.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IdlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
public interface IIdlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.idlFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdlFile([NotNull] IdlParser.IdlFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.idlFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdlFile([NotNull] IdlParser.IdlFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.protocolDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocolDeclaration([NotNull] IdlParser.ProtocolDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.protocolDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocolDeclaration([NotNull] IdlParser.ProtocolDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.protocolDeclarationBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocolDeclarationBody([NotNull] IdlParser.ProtocolDeclarationBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.protocolDeclarationBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocolDeclarationBody([NotNull] IdlParser.ProtocolDeclarationBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceDeclaration([NotNull] IdlParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceDeclaration([NotNull] IdlParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.mainSchemaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainSchemaDeclaration([NotNull] IdlParser.MainSchemaDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.mainSchemaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainSchemaDeclaration([NotNull] IdlParser.MainSchemaDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] IdlParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] IdlParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.schemaProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSchemaProperty([NotNull] IdlParser.SchemaPropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.schemaProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSchemaProperty([NotNull] IdlParser.SchemaPropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStatement([NotNull] IdlParser.ImportStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStatement([NotNull] IdlParser.ImportStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.namedSchemaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedSchemaDeclaration([NotNull] IdlParser.NamedSchemaDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.namedSchemaDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedSchemaDeclaration([NotNull] IdlParser.NamedSchemaDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.fixedDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedDeclaration([NotNull] IdlParser.FixedDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.fixedDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedDeclaration([NotNull] IdlParser.FixedDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclaration([NotNull] IdlParser.EnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclaration([NotNull] IdlParser.EnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.enumSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumSymbol([NotNull] IdlParser.EnumSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.enumSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumSymbol([NotNull] IdlParser.EnumSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.enumDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDefault([NotNull] IdlParser.EnumDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.enumDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDefault([NotNull] IdlParser.EnumDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.recordDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordDeclaration([NotNull] IdlParser.RecordDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.recordDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordDeclaration([NotNull] IdlParser.RecordDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.recordBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordBody([NotNull] IdlParser.RecordBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.recordBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordBody([NotNull] IdlParser.RecordBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaration([NotNull] IdlParser.FieldDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaration([NotNull] IdlParser.FieldDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] IdlParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] IdlParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.messageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageDeclaration([NotNull] IdlParser.MessageDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.messageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageDeclaration([NotNull] IdlParser.MessageDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameter([NotNull] IdlParser.FormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameter([NotNull] IdlParser.FormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.resultType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResultType([NotNull] IdlParser.ResultTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.resultType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResultType([NotNull] IdlParser.ResultTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.fullType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFullType([NotNull] IdlParser.FullTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.fullType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFullType([NotNull] IdlParser.FullTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.plainType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlainType([NotNull] IdlParser.PlainTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.plainType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlainType([NotNull] IdlParser.PlainTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.nullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullableType([NotNull] IdlParser.NullableTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.nullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullableType([NotNull] IdlParser.NullableTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] IdlParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] IdlParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayType([NotNull] IdlParser.ArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayType([NotNull] IdlParser.ArrayTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.mapType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapType([NotNull] IdlParser.MapTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.mapType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapType([NotNull] IdlParser.MapTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionType([NotNull] IdlParser.UnionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionType([NotNull] IdlParser.UnionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonValue([NotNull] IdlParser.JsonValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonValue([NotNull] IdlParser.JsonValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonLiteral([NotNull] IdlParser.JsonLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonLiteral([NotNull] IdlParser.JsonLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonObject([NotNull] IdlParser.JsonObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonObject([NotNull] IdlParser.JsonObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonPair([NotNull] IdlParser.JsonPairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonPair([NotNull] IdlParser.JsonPairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdlParser.jsonArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonArray([NotNull] IdlParser.JsonArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdlParser.jsonArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonArray([NotNull] IdlParser.JsonArrayContext context);
}
